name: bazar_suez
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª iOS
  cupertino_icons: ^1.0.2

  # ğŸ”¥ Ù…ÙƒØªØ¨Ø§Øª Firebase (Ù…ØªÙˆØ§ÙÙ‚Ø© Ù…Ø¹ Ø¨Ø¹Ø¶ - Ø¨Ø¯ÙˆÙ† ØªØ¹Ø§Ø±Ø¶)
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.4
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_database: ^12.0.3

  # ğŸŒ Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„ØªÙˆØ¬ÙŠÙ‡ ÙˆØ¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø§Ù„Ø©
  go_router: ^16.2.5
  provider: ^6.1.5

  # ğŸ” ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.2

  # ğŸ¨ ÙˆØ§Ø¬Ù‡Ø© Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… ÙˆØ§Ù„ØªØ­Ø³ÙŠÙ†Ø§Øª
  font_awesome_flutter: ^10.2.0
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1
  flutter_custom_clippers: ^2.0.0

  # ğŸ“± ØµÙ„Ø§Ø­ÙŠØ§Øª ÙˆØµÙˆØ± ÙˆÙ…Ø´Ø§Ø±ÙƒØ©
  permission_handler: ^12.0.1
  image_picker: ^1.0.8
  share_plus: ^12.0.1
  url_launcher: ^6.3.0

  # ğŸŒ Ø§Ù„Ø®Ø±Ø§Ø¦Ø· ÙˆØ§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¬ØºØ±Ø§ÙÙŠ
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # âš™ï¸ Ø£Ø¯ÙˆØ§Øª Ù…Ø³Ø§Ø¹Ø¯Ø©
  uuid: ^4.5.1
  http: ^1.1.0
  hive_flutter: ^1.1.0
  google_places_flutter: ^2.1.1
  fl_chart: ^1.1.1

  
  # ğŸ’³ Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ø¯ÙØ¹
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/egypt.jpg
    - assets/images/food_placeholder.png
    - assets/images/logo.png
    - assets/images/categories/
    - assets/images/create_market.png
    

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700